---
title: "report_normalizations"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
    html_document:
        fig_height: 9
        fig_width: 9
        toc: yes
        code_folding: hide
        toc_float: yes
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE}
knitr::opts_chunk$set(eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE,
                      fig.width=9, fig.height=9)
source("../R/utilities.R")
source("../R/filterLowCounts.R")
source("../R/plotFunctions.R")
source("../R/normalizationFunctions.R")
library(plotly)
library(RUVSeq)
```
###Importing data
```{r eval=TRUE, echo=TRUE, warning=FALSE, message=TRUE}
countMatrix <- ReadDataFrameFromTsv(file.name.path="../data/refSEQ_countMatrix.txt")
# head(countMatrix)

designMatrix <- ReadDataFrameFromTsv(file.name.path="../design/all_samples_short_names.tsv.csv")
# head(designMatrix)

filteredCountsProp <- filterLowCounts(counts.dataframe=countMatrix, 
                                    is.normalized=FALSE,
                                    design.dataframe=designMatrix,
                                    cond.col.name="gcondition",
                                    method.type="Proportion")
```


##Plot PCA of log unnormalized data
```{r eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}

pc1_2 <- PlotPCAPlotlyFunction(counts.data.frame=log1p(filteredCountsProp), design.matrix=designMatrix, shapeColname="classic", colorColname="gcondition", xPCA="PC1", yPCA="PC2", plotly.flag=TRUE, show.plot.flag=FALSE, prefix.plot="Prop-Un-Norm")
pc2_3 <- PlotPCAPlotlyFunction(counts.data.frame=log1p(filteredCountsProp), design.matrix=designMatrix, shapeColname="classic", colorColname="gcondition", xPCA="PC2", yPCA="PC3", plotly.flag=TRUE, show.plot.flag=FALSE, prefix.plot="Prop-Un-Norm")
pc1_3 <- PlotPCAPlotlyFunction(counts.data.frame=log1p(filteredCountsProp), design.matrix=designMatrix, shapeColname="classic", colorColname="gcondition", xPCA="PC1", yPCA="PC3", plotly.flag=TRUE, show.plot.flag=FALSE, prefix.plot="Prop-Un-Norm")
plotly::subplot(pc1_2, pc2_3, pc1_3, nrows=2, margin = 0.1, titleX=TRUE, titleY=TRUE)
```

##Normalizations
###Upper Quartile Normalization
```{r eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}

normPropCountsUqua <- NormalizeData(data.to.normalize=filteredCountsProp, 
                                    norm.type="uqua", 
                                    design.matrix=designMatrix)

pc1_2 <- PlotPCAPlotlyFunction(counts.data.frame=log1p(normPropCountsUqua), design.matrix=designMatrix, shapeColname="classic", colorColname="gcondition", xPCA="PC1", yPCA="PC2", plotly.flag=TRUE, show.plot.flag=FALSE, prefix.plot="UQUA-Norm")
pc2_3 <- PlotPCAPlotlyFunction(counts.data.frame=log1p(normPropCountsUqua), design.matrix=designMatrix, shapeColname="classic", colorColname="gcondition", xPCA="PC2", yPCA="PC3", plotly.flag=TRUE, show.plot.flag=FALSE, prefix.plot="UQUA-Norm")
pc1_3 <- PlotPCAPlotlyFunction(counts.data.frame=log1p(normPropCountsUqua), design.matrix=designMatrix, shapeColname="classic", colorColname="gcondition", xPCA="PC1", yPCA="PC3", plotly.flag=TRUE, show.plot.flag=FALSE, prefix.plot="UQUA-Norm")
plotly::subplot(pc1_2, pc2_3, pc1_3, nrows=2, margin = 0.1, titleX=TRUE, titleY=TRUE)
```

## edgeR DE Analysis
```{r}
### edgering
source("../R/edgeRFunctions.R")
source("../R/VolcanoPlotFunctions.R")
source("../R/plotUtils.R")
source("../R/MAPlotFunctions.R")
source("../R/pvalHistPlotFunctions.R")
source("../R/plotUtils.R")

cc <- c("WTSD5 - WTHC5", "WTRS2 - WTHC7")

rescList1 <- applyEdgeR(counts=normPropCountsUqua, design.matrix=designMatrix,
                        factors.column="gcondition", 
                        weight.columns=NULL,
                        contrasts=cc, useIntercept=FALSE, p.threshold=1,
                        verbose=TRUE)
```

### WTSD5 vs WTHC5
```{r}
PlotHistPvalPlot(de.results=rescList1[[1]], design.matrix=designMatrix, 
                show.plot.flag=TRUE, plotly.flag=TRUE, 
                prefix.plot=names(rescList1)[1])
```

### SD loading positive controls
```{r eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
sd.pos.ctrls <- ReadDataFrameFromTsv(file.name.path="data/SD_full_pos_control_genes_BMC_genomics.csv")

sd.pos.ctrls <- sd.pos.ctrls$MGI.Symbol

sd.pos.map <- convertGenesViaBiomart(specie="mm10", filter="mgi_symbol",
                    filter.values=sd.pos.ctrls, c("external_gene_name",
                                "mgi_symbol", "entrezgene"))

sd.pos.map.nna <- sd.pos.map[-which(is.na(sd.pos.map$entrezgene)),]

sd.pos.genes.entrez <- sd.pos.map.nna$entrezgene


```

```{r eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
library(biomaRt)
res.o.map <- convertGenesViaBiomart(specie="mm10", filter="entrezgene",
                            filter.values=rownames(rescList1[[1]]), 
                            c("external_gene_name", "mgi_symbol", "entrezgene"))


res.o <- attachGeneColumnToDf(mainDf=rescList1[[1]],
                                genesMap=res.o.map,
                                rowNamesIdentifier="entrezgene",
                                mapFromIdentifier="entrezgene",
                                mapToIdentifier="external_gene_name")

PlotVolcanoPlot(de.results=res.o, counts.dataframe=normExprData, design.matrix=designMatrix,
                show.plot.flag=TRUE, plotly.flag=TRUE, save.plot=FALSE, prefix.plot=names(rescList1)[1], threshold=0.05, 
                positive.ctrls.list=sd.pos.genes.entrez)
PlotMAPlotCounts(de.results=res.o, counts.dataframe=normExprData, design.matrix=desMat,
                 show.plot.flag=TRUE, plotly.flag=TRUE, save.plot=FALSE, prefix.plot=names(rescList1)[1], threshold=0.05)

```

### KORS2 vs KOHC7
```{r}
PlotHistPvalPlot(de.results=rescList1[[2]], design.matrix=desMat, 
                show.plot.flag=TRUE, plotly.flag=TRUE, 
                prefix.plot=names(rescList1)[2])
```

```{r eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
## mapping ensembl gene id using biomart
library(biomaRt)

names <- as.integer(rownames(rescList1[[2]])[order(rownames(rescList1[[2]]))])

mart = useMart('ENSEMBL_MART_ENSEMBL',dataset='mmusculus_gene_ensembl', 
                host="may2012.archive.ensembl.org") ## using mm9
attrs <- c("ensembl_gene_id", "external_gene_id", "entrezgene")
gene.map <- getBM(attributes=attrs, mart=mart, filters="entrezgene", 
                  values=names)

## gene.map
gm.no.dp <- gene.map[-which(duplicated(gene.map$entrezgene)),]
ind.gm <- which(gm.no.dp$entrezgene %in% names)
gm.no.dpigm <- gm.no.dp[ind.gm,]
gm.no.dpigm.o <- gm.no.dpigm[order(gm.no.dpigm$entrezgene),]

## names
ind.nm <- which(names %in% gene.map$entrezgene)
names.gm <- names[ind.nm]
names.gm.o <- names.gm[order(names.gm)]
ndf.map <- cbind.data.frame(gm.no.dpigm.o,
                    names.gm.o)

res.o <- rescList1[[2]][order(as.integer(rownames(rescList1[[2]]))),]

ind.rn <- which(as.integer(rownames(res.o)) %in% ndf.map$names.gm.o)
res.o$map <- NA
# filtCountsProp.o$ensmap <- NA
res.o$map[ind.rn] <- ndf.map$external_gene_id

PlotVolcanoPlot(de.results=res.o, counts.dataframe=normExprData, design.matrix=desMat,
                show.plot.flag=TRUE, plotly.flag=TRUE, save.plot=FALSE, prefix.plot=names(rescList1)[2], threshold=0.05)
PlotMAPlotCounts(de.results=res.o, counts.dataframe=normExprData, design.matrix=desMat,
                 show.plot.flag=TRUE, plotly.flag=TRUE, save.plot=FALSE, prefix.plot=names(rescList1)[2], threshold=0.05)
```

### WTSD5 vs WTHC5
```{r}
PlotHistPvalPlot(de.results=rescList1[[3]], design.matrix=desMat, 
                show.plot.flag=TRUE, plotly.flag=TRUE, 
                prefix.plot=names(rescList1)[3])
```

```{r eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
## mapping ensembl gene id using biomart
library(biomaRt)

names <- as.integer(rownames(rescList1[[3]])[order(rownames(rescList1[[3]]))])

mart = useMart('ENSEMBL_MART_ENSEMBL',dataset='mmusculus_gene_ensembl', 
                host="may2012.archive.ensembl.org") ## using mm9
attrs <- c("ensembl_gene_id", "external_gene_id", "entrezgene")
gene.map <- getBM(attributes=attrs, mart=mart, filters="entrezgene", 
                  values=names)

## gene.map
gm.no.dp <- gene.map[-which(duplicated(gene.map$entrezgene)),]
ind.gm <- which(gm.no.dp$entrezgene %in% names)
gm.no.dpigm <- gm.no.dp[ind.gm,]
gm.no.dpigm.o <- gm.no.dpigm[order(gm.no.dpigm$entrezgene),]

## names
ind.nm <- which(names %in% gene.map$entrezgene)
names.gm <- names[ind.nm]
names.gm.o <- names.gm[order(names.gm)]
ndf.map <- cbind.data.frame(gm.no.dpigm.o,
                    names.gm.o)

res.o <- rescList1[[3]][order(as.integer(rownames(rescList1[[3]]))),]

ind.rn <- which(as.integer(rownames(res.o)) %in% ndf.map$names.gm.o)
res.o$map <- NA
# filtCountsProp.o$ensmap <- NA
res.o$map[ind.rn] <- ndf.map$external_gene_id

PlotVolcanoPlot(de.results=res.o, counts.dataframe=normExprData, design.matrix=desMat,
                show.plot.flag=TRUE, plotly.flag=TRUE, save.plot=FALSE, prefix.plot=names(rescList1)[3], threshold=0.05)
PlotMAPlotCounts(de.results=res.o, counts.dataframe=normExprData, design.matrix=desMat,
                 show.plot.flag=TRUE, plotly.flag=TRUE, save.plot=FALSE, prefix.plot=names(rescList1)[3], threshold=0.05)
```

### WTRS2 vs WTHC7
```{r}
PlotHistPvalPlot(de.results=rescList1[[4]], design.matrix=desMat, 
                show.plot.flag=TRUE, plotly.flag=TRUE, 
                prefix.plot=names(rescList1)[4])
```

```{r eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
## mapping ensembl gene id using biomart
library(biomaRt)

names <- as.integer(rownames(rescList1[[4]])[order(rownames(rescList1[[4]]))])

mart = useMart('ENSEMBL_MART_ENSEMBL',dataset='mmusculus_gene_ensembl', 
                host="may2012.archive.ensembl.org") ## using mm9
attrs <- c("ensembl_gene_id", "external_gene_id", "entrezgene")
gene.map <- getBM(attributes=attrs, mart=mart, filters="entrezgene", 
                  values=names)

## gene.map
gm.no.dp <- gene.map[-which(duplicated(gene.map$entrezgene)),]
ind.gm <- which(gm.no.dp$entrezgene %in% names)
gm.no.dpigm <- gm.no.dp[ind.gm,]
gm.no.dpigm.o <- gm.no.dpigm[order(gm.no.dpigm$entrezgene),]

## names
ind.nm <- which(names %in% gene.map$entrezgene)
names.gm <- names[ind.nm]
names.gm.o <- names.gm[order(names.gm)]
ndf.map <- cbind.data.frame(gm.no.dpigm.o,
                    names.gm.o)

res.o <- rescList1[[4]][order(as.integer(rownames(rescList1[[4]]))),]

ind.rn <- which(as.integer(rownames(res.o)) %in% ndf.map$names.gm.o)
res.o$map <- NA
# filtCountsProp.o$ensmap <- NA
res.o$map[ind.rn] <- ndf.map$external_gene_id

PlotVolcanoPlot(de.results=res.o, counts.dataframe=normExprData, design.matrix=desMat,
                show.plot.flag=TRUE, plotly.flag=TRUE, save.plot=FALSE, prefix.plot=names(rescList1)[4], threshold=0.05)
PlotMAPlotCounts(de.results=res.o, counts.dataframe=normExprData, design.matrix=desMat,
                 show.plot.flag=TRUE, plotly.flag=TRUE, save.plot=FALSE, prefix.plot=names(rescList1)[4], threshold=0.05)
```










